config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'

  post 'tasks', to: 'tasks#create'
  get 'tasks/new', to: 'tasks#new'

  get 'tasks/:id', to: 'tasks#show', as: :task

  get 'tasks/:id/edit', to: 'tasks#edit', as: :task_edit
  patch 'tasks/:id', to: 'tasks#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
  end

  def edit
    @task = Task.find(params[:id])

  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>

</html>

app/views/tasks/edit.html.erb
<form action="/tasks" method="patch">
  <h2>Edit task</h2>
  <div class="form-group">
    <label for="enterTitle">Title</label>
    <input type="text" class="form-control" id="enterTitle" name="task[title]" value=<%= @task.title %>>

  </div>
  <div class="form-group">
    <label for="enterDetails">Details</label>
    <input type="text" class="form-control" id="enterDetails" name="task[details]" value=<%= @task.details %>>
  </div>
  <div class="form-group form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Completed</label>
  </div>
  <button type="submit" class="btn btn-primary">Update Task</button>
</form>

<div>
  <%= link_to "Back to List", tasks_path%>
</div>

app/views/tasks/index.html.erb
<h1>My tasks</h1>



<% @tasks.each do |task|%>
<div class="container">
  <% if task.completed == true %>
    <input type="checkbox" name="tasks" checked>
  <% else %>
    <input type="checkbox" name="tasks" value= <%= task.title%>>
  <% end %>
    <label for="tasks"> <%= link_to task.title, task_path(task)%></label>
</div>
<% end %>

<div>

<%= link_to "Add a new task", tasks_new_path%>

</div>

app/views/tasks/new.html.erb
<h2>New Task</h2>

<form action="/tasks" method="post" class="form_container">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <div class="form-group">
  <label for="title">Title:</label>
  <input type="text" name="task[title]" id="title" class="form-control">
  </div>

  <div class="form-group">
  <label for="details">Details:</label>
  <input type="text" name="task[details]" id="details" class="form-control">
  </div>
  <div>  <input type="submit" class="buttoncreate" value="Create task"></div>

  <div class="backlist">
   <%= link_to "Back to List", tasks_path%>
  </div>

</form>

app/views/tasks/show.html.erb
<form action=" " method="get">
<div>
  <h2> <%= @task.title %></h2>
  <button type="submit" class="btn btn-secondary">Edit this task</button>
</div>
</form>

<div class="details-box">
  <%= @task.details%>
</div>


<% if @task.completed == true %>
  <input type="checkbox" id="status" name="vehicle1" value="Bike" checked>
  <label for="status"> This task is completed</label><br>
<% else %>
  <input type="checkbox" id="status" name="vehicle1" value="Bike">
  <label for="status"> This task is not completed yet</label><br>
<% end %>
<br><br> <br><br>

<%= link_to "Back to list", tasks_path%>